# -*- coding: utf-8 -*-
"""PRODIGY_DS_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PcYez2LWGY9y-rHyGY8-mtlLO1TRf4p_
"""

#Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Read and load data:
df = pd.read_csv('/content/drive/MyDrive/Prodigy_Internship/adult.csv')

df.info()

print(df.head())

#Histogram for Age distribution:
plt.figure(figsize=(10,6))
sns.histplot(df['age'],bins=30,kde=True, color='red')

# Add title and labels
plt.title('Distribution of Age')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

#Bar graph for gender distribution:
plt.figure(figsize=(8, 6))
sns.countplot(x='gender', data=df, palette='Set2')

# Add title and labels
plt.title('Distribution of Gender')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.show()

